apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildpack
  namespace: apps
  labels:
    app: buildpack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buildpack
  template:
    metadata:
      labels:
        app: buildpack
    spec:
      containers:
      - name: buildpack
        image: maxmorhardt/jenkins-buildpack:latest
        ports:
        - containerPort: 80